#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_dir=$(cd "${script_dir}/.." && pwd)
fixture_dir="${repo_dir}/tests/fixtures/tiny_hal"
build_dir="${fixture_dir}/build"

for tool in maf2hal halStats halLiftover; do
  if ! command -v "${tool}" >/dev/null 2>&1; then
    echo "error: required HAL tool '${tool}' is not on PATH" >&2
    echo "Install the pinned HAL tools environment documented in .github/workflows/ci.yml." >&2
    exit 2
  fi
done

rm -rf "${build_dir}"
mkdir -p "${build_dir}"

cat > "${build_dir}/root.maf" <<'MAF'
##maf version=1 scoring=tiny-hal

a score=0
s HAL_root.chrRoot  0 120 + 120 AAAAAAAAAACCCCCCCCCCGGGGGGGGGGTTTTTTTTTTAAAAAAAAAACCCCCCCCCCGGGGGGGGGGTTTTTTTTTTAAAAAAAAAACCCCCCCCCC
s HAL_ancAB.chrAB   0 120 + 120 AAAAAAAAAACCCCCCCCCCGGGGGGGGGGTTTTTTTTTTAAAAAAAAAACCCCCCCCCCGGGGGGGGGGTTTTTTTTTTAAAAAAAAAACCCCCCCCCC
s HAL_ancCD.chrCD   0 120 + 120 AAAAAAAAAACCCCCCCCCCGGGGGGGGGGTTTTTTTTTTAAAAAAAAAACCCCCCCCCCGGGGGGGGGGTTTTTTTTTTAAAAAAAAAACCCCCCCCCC
MAF

cat > "${build_dir}/ancAB.maf" <<'MAF'
##maf version=1 scoring=tiny-hal

a score=0
s HAL_ancAB.chrAB 0 10 + 120 AAAAAAAAAA
s HAL_A.chrA     0 10 + 100 AAAAAAAAAA
s HAL_B.chrB     0 10 + 100 AAAAAAAAAA

a score=0
s HAL_ancAB.chrAB 20 10 + 120 GGGGGGGGGG
s HAL_A.chrA     80 10 - 100 GGGGGGGGGG
s HAL_B.chrB     10 10 + 100 GGGGGGGGGG

a score=0
s HAL_ancAB.chrAB 60 10 + 120 AAAAAAAAAA
s HAL_A.chrA     60 10 + 100 AAAAAAAAAA

a score=0
s HAL_ancAB.chrAB 80 10 + 120 CCCCCCCCCC
s HAL_A.chrA     70 10 + 100 CCCCCCCCCC
MAF

cat > "${build_dir}/ancCD.maf" <<'MAF'
##maf version=1 scoring=tiny-hal

a score=0
s HAL_ancCD.chrCD 0 10 + 120 AAAAAAAAAA
s HAL_C.chrC      0 10 + 100 AAAAAAAAAA
s HAL_D.chrD      0 10 + 100 AAAAAAAAAA
MAF

maf2hal "${build_dir}/root.maf" "${build_dir}/tiny.hal" \
  --refGenome HAL_root \
  --targetGenomes HAL_ancAB,HAL_ancCD
maf2hal "${build_dir}/ancAB.maf" "${build_dir}/tiny.hal" \
  --append \
  --refGenome HAL_ancAB \
  --targetGenomes HAL_A,HAL_B
maf2hal "${build_dir}/ancCD.maf" "${build_dir}/tiny.hal" \
  --append \
  --refGenome HAL_ancCD \
  --targetGenomes HAL_C,HAL_D

halStats "${build_dir}/tiny.hal" --genomes > "${build_dir}/hal-genomes.txt"
halStats "${build_dir}/tiny.hal" --tree > "${build_dir}/hal-tree.nwk"

cat > "${build_dir}/README.generated.txt" <<EOF2
Generated by scripts/build_tiny_hal_fixture.sh
maf2hal: $(maf2hal --version 2>&1 | head -n 1 || true)
halStats: $(halStats --version 2>&1 | head -n 1 || true)
halLiftover: $(halLiftover --version 2>&1 | head -n 1 || true)
EOF2

echo "wrote ${build_dir}/tiny.hal"
